
export const CHECK_AUTH = 'CHECK_AUTH'
export const DECODE_TOKEN = 'DECODE_TOKEN'
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const GET_ALL_EMPLOYEE = 'GET_ALL_EMPLOYEE'
export const GET_ALL_PROPERTIES = 'GET_ALL_PROPERTIES'